#pragma once

#define MK_COMBINED

#define MOUSEKEY_DELAY	10
#define MOUSEKEY_INTERVAL	20
#define MOUSEKEY_MOVE_DELTA	8
#define MOUSEKEY_MAX_SPEED7	7	
#define MOUSEKEY_TIME_TO_MAX	48

#define MOUSEKEY_WHEEL_DELAY	10
#define MOUSEKEY_WHEEL_INTERVAL	80
#define MOUSEKEY_WHEEL_DELTA	1
#define MOUSEKEY_WHEEL_MAX_SPEED	8
#define MOUSEKEY_WHEEL_TIME_TO_MAX	40
